FROM registry.access.redhat.com/ubi8/nodejs-18:1 as build

ENV PORT 3000
ENV NODE_HEAPDUMP_OPTIONS nosignal
EXPOSE 3000
EXPOSE 9229

USER root

CMD ["/bin/bash"]
ARG bx_dev_user=root
ARG bx_dev_userid=1000
RUN BX_DEV_USER=$bx_dev_user
RUN BX_DEV_USERID=$bx_dev_userid
RUN if [ "$bx_dev_user" != root ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi
RUN chown -R $bx_dev_user /opt/app-root

USER $bx_dev_user
WORKDIR /opt/app-root/src
COPY . /opt/app-root/src
